// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto.Data;

#nullable disable

namespace Proyecto.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto.Models.Bodegas", b =>
                {
                    b.Property<int>("IdBodegas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBodegas"));

                    b.Property<string>("DireccionExacta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCanton")
                        .HasColumnType("int");

                    b.Property<int>("IdDistrito")
                        .HasColumnType("int");

                    b.Property<int>("IdProvincia")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBodegas");

                    b.HasIndex("IdCanton");

                    b.HasIndex("IdDistrito");

                    b.HasIndex("IdProvincia");

                    b.ToTable("Bodegas");
                });

            modelBuilder.Entity("Proyecto.Models.Canton", b =>
                {
                    b.Property<int>("IdCanton")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCanton"));

                    b.Property<int>("IdProvincia")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCanton");

                    b.HasIndex("IdProvincia");

                    b.ToTable("Canton");
                });

            modelBuilder.Entity("Proyecto.Models.Distrito", b =>
                {
                    b.Property<int>("IdDistrito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDistrito"));

                    b.Property<int>("IdCanton")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDistrito");

                    b.HasIndex("IdCanton");

                    b.ToTable("Distrito");
                });

            modelBuilder.Entity("Proyecto.Models.Facturas", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFactura"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<decimal?>("MontoDeuda")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Pendiente")
                        .HasColumnType("bit");

                    b.HasKey("IdFactura");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("Proyecto.Models.Pedidos", b =>
                {
                    b.Property<int>("IdPedidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedidos"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProveedores")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdPedidos");

                    b.HasIndex("IdProveedores");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Proyecto.Models.ProductoFactura", b =>
                {
                    b.Property<int>("IdProductoFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProductoFactura"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("IdFactura")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdProductoFactura");

                    b.HasIndex("IdFactura");

                    b.HasIndex("IdProducto");

                    b.ToTable("ProductoFactura");
                });

            modelBuilder.Entity("Proyecto.Models.ProductoProveedores", b =>
                {
                    b.Property<int>("IdProductoProveedores")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProductoProveedores"));

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdProductoProveedores");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdProveedor");

                    b.ToTable("ProductoProveedores");
                });

            modelBuilder.Entity("Proyecto.Models.Productos", b =>
                {
                    b.Property<int>("IdProductos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProductos"));

                    b.Property<int>("CantidadEmpaque")
                        .HasColumnType("int");

                    b.Property<int>("CantidadPresentacion")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Presentacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoEmpaque")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProductos");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Proyecto.Models.ProductosBodega", b =>
                {
                    b.Property<int>("IdProductoBodega")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProductoBodega"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdBodega")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.HasKey("IdProductoBodega");

                    b.HasIndex("IdBodega");

                    b.HasIndex("IdProducto");

                    b.ToTable("ProductosBodega");
                });

            modelBuilder.Entity("Proyecto.Models.ProductosPedidos", b =>
                {
                    b.Property<int>("IdProductosPedidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProductosPedidos"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("IdPedidos")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.HasKey("IdProductosPedidos");

                    b.HasIndex("IdPedidos");

                    b.HasIndex("IdProducto");

                    b.ToTable("ProductosPedidos");
                });

            modelBuilder.Entity("Proyecto.Models.Proveedores", b =>
                {
                    b.Property<int>("IdProveedores")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProveedores"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionExacta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCanton")
                        .HasColumnType("int");

                    b.Property<int>("IdDistrito")
                        .HasColumnType("int");

                    b.Property<int>("IdProvincia")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProveedores");

                    b.HasIndex("IdCanton");

                    b.HasIndex("IdDistrito");

                    b.HasIndex("IdProvincia");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("Proyecto.Models.Provincia", b =>
                {
                    b.Property<int>("IdProvincia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProvincia"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProvincia");

                    b.ToTable("Provincia");
                });

            modelBuilder.Entity("Proyecto.Models.Usuarios", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdBodega")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdBodega");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Proyecto.Models.Bodegas", b =>
                {
                    b.HasOne("Proyecto.Models.Canton", "Canton")
                        .WithMany("Bodegas")
                        .HasForeignKey("IdCanton")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto.Models.Distrito", "Distrito")
                        .WithMany("Bodegas")
                        .HasForeignKey("IdDistrito")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto.Models.Provincia", "Provincia")
                        .WithMany("Bodegas")
                        .HasForeignKey("IdProvincia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Canton");

                    b.Navigation("Distrito");

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("Proyecto.Models.Canton", b =>
                {
                    b.HasOne("Proyecto.Models.Provincia", "Provincia")
                        .WithMany("Cantones")
                        .HasForeignKey("IdProvincia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("Proyecto.Models.Distrito", b =>
                {
                    b.HasOne("Proyecto.Models.Canton", "Canton")
                        .WithMany("Distritos")
                        .HasForeignKey("IdCanton")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Canton");
                });

            modelBuilder.Entity("Proyecto.Models.Facturas", b =>
                {
                    b.HasOne("Proyecto.Models.Proveedores", "Proveedor")
                        .WithMany("Facturas")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto.Models.Usuarios", "Usuario")
                        .WithMany("Facturas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proveedor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proyecto.Models.Pedidos", b =>
                {
                    b.HasOne("Proyecto.Models.Proveedores", "Proveedores")
                        .WithMany()
                        .HasForeignKey("IdProveedores")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto.Models.Usuarios", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proveedores");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proyecto.Models.ProductoFactura", b =>
                {
                    b.HasOne("Proyecto.Models.Facturas", "Factura")
                        .WithMany("ProductoFactura")
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto.Models.Productos", "Producto")
                        .WithMany("ProductoFactura")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Proyecto.Models.ProductoProveedores", b =>
                {
                    b.HasOne("Proyecto.Models.Productos", "Productos")
                        .WithMany("ProductoProveedores")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto.Models.Proveedores", "Proveedores")
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Productos");

                    b.Navigation("Proveedores");
                });

            modelBuilder.Entity("Proyecto.Models.ProductosBodega", b =>
                {
                    b.HasOne("Proyecto.Models.Bodegas", "Bodegas")
                        .WithMany("ProductosBodega")
                        .HasForeignKey("IdBodega")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto.Models.Productos", "Productos")
                        .WithMany("ProductosBodega")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bodegas");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Proyecto.Models.ProductosPedidos", b =>
                {
                    b.HasOne("Proyecto.Models.Pedidos", "Pedido")
                        .WithMany("ProductosPedidos")
                        .HasForeignKey("IdPedidos")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto.Models.Productos", "Producto")
                        .WithMany("ProductosPedidos")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Proyecto.Models.Proveedores", b =>
                {
                    b.HasOne("Proyecto.Models.Canton", "Canton")
                        .WithMany("Proveedores")
                        .HasForeignKey("IdCanton")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto.Models.Distrito", "Distrito")
                        .WithMany("Proveedores")
                        .HasForeignKey("IdDistrito")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Proyecto.Models.Provincia", "Provincia")
                        .WithMany("Proveedores")
                        .HasForeignKey("IdProvincia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Canton");

                    b.Navigation("Distrito");

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("Proyecto.Models.Usuarios", b =>
                {
                    b.HasOne("Proyecto.Models.Bodegas", "Bodegas")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdBodega")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bodegas");
                });

            modelBuilder.Entity("Proyecto.Models.Bodegas", b =>
                {
                    b.Navigation("ProductosBodega");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Proyecto.Models.Canton", b =>
                {
                    b.Navigation("Bodegas");

                    b.Navigation("Distritos");

                    b.Navigation("Proveedores");
                });

            modelBuilder.Entity("Proyecto.Models.Distrito", b =>
                {
                    b.Navigation("Bodegas");

                    b.Navigation("Proveedores");
                });

            modelBuilder.Entity("Proyecto.Models.Facturas", b =>
                {
                    b.Navigation("ProductoFactura");
                });

            modelBuilder.Entity("Proyecto.Models.Pedidos", b =>
                {
                    b.Navigation("ProductosPedidos");
                });

            modelBuilder.Entity("Proyecto.Models.Productos", b =>
                {
                    b.Navigation("ProductoFactura");

                    b.Navigation("ProductoProveedores");

                    b.Navigation("ProductosBodega");

                    b.Navigation("ProductosPedidos");
                });

            modelBuilder.Entity("Proyecto.Models.Proveedores", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("Proyecto.Models.Provincia", b =>
                {
                    b.Navigation("Bodegas");

                    b.Navigation("Cantones");

                    b.Navigation("Proveedores");
                });

            modelBuilder.Entity("Proyecto.Models.Usuarios", b =>
                {
                    b.Navigation("Facturas");
                });
#pragma warning restore 612, 618
        }
    }
}
